apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-3
  namespace: qos-example
spec:
  containers:
  - name: qos-demo-3-ctr
    image: nginx

#If no Limit and Request is given, then it comes under BestEffort Class
#kubectl create namespace qos-example
#kubectl delete pod qos-demo-3 --namespace=qos-example