apiVersion: apps/v1
kind: Deployment
metadata:
  name: np-deployment
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: np-demo-continer
        image: lerndevops/samplepyapp:v2
        ports:
        - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: np-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 3000