apiVersion: v1
kind: Pod
metadata:
  name: label-example
  labels:
    name: label-demo
    env: development
    app: nginx
spec:
  containers:
  - name: mycontainer
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80